# Generated by Django 5.1.2 on 2024-10-20 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="name",
            new_name="title",
        ),
    ]
