# Generated by Django 5.1.2 on 2024-10-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_name_menu_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
    ]
